### ISSUE TITLE
SSL Certifcate password Support

### ISSUE THREAD

**Issue by taylormd** [Intelworks/cabby#22]
So I was trying to locate anything that on the pages that showed cabby supports certificates that require passwords. If not, this is something that many organizations are looking to have implemented.

**Comment by traut** [comment]
@taylormd interesting suggestion, thanks! I'll investigate and update this issue with the results

**Comment by traut** [comment]
@taylormd implemented in trunk. Waiting for libtaxii to release new version, so we can release new cabby version
