### ISSUE TITLE
Use console script entry points instead of scripts directory

### ISSUE THREAD

**Issue by wbolster** [Intelworks/cabby#6]
The benefits of using console script entry points is that the actual scripts can live inside the package, and can use the module name for e.g. logger names. It will also make it easier to install on non posix platforms. Additionally it makes it easier to use the tools from within a virtualenv without first activating it.  (Ideally something like `pipsi install taxii-client` should make the cli programs available.)

**Comment by traut** [comment]
implemented in #17
